### ISSUE TITLE
Run e2e test on BTP Manager installed from template.yaml

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#135]
**Description**

This ticket is about changing the way how to install BTP-Manager in our: https://github.com/kyma-project/btp-manager/blob/main/testing/go/e2e_test.go. Instead of ```make deploy``` we must install BTP Manager in the same way how Lifecycle Manager does. 

Of course, testing Lifecycle Manager is not in our scope, which means we need to reuse ~~our generated template.yaml~ OCI image and out of that install BTP-Manager for testing purposes.

**AC**

- [x] 1) Generate module for PRs that results with ~~template.yaml~~ OCI image
  - [x] 1.1) ~~find a way where to store template.yaml for PR pipeline, that will be required for next steps~~ this is not longer necessary since OCI image is stored in registry  
- [x] 2) ~~Adjust release pipeline to use the same way of storing template.yaml as in PR (Still keep template.yaml in the release itself)~~ not valid any more, we are not storing template.yaml in PR
- [x] 3) download OCI image, unpack it, install
- [x] 4) describe in our documentation how and what is tested in our e2e tests
- [x] 5) try store OCI images ~~and templates~~ in the local registry (we use k3d for testing)

**Comment by jaroslaw-pieszka** [comment]
During discussions with @PK85 and @piotrmiskiewicz we agreed to use OCI image only, not to use template.yaml

**Comment by jaroslaw-pieszka** [comment]
[Prow job](https://github.com/kyma-project/test-infra/pull/6975) - creating OCI module image for PR (presubmit job)

**Comment by jaroslaw-pieszka** [comment]
[Initial version - stub](https://github.com/kyma-project/btp-manager/pull/181) of script creating the module image (via make invocation)

**Comment by jaroslaw-pieszka** [comment]
[WIP](https://github.com/kyma-project/btp-manager/pull/176)

**Comment by jaroslaw-pieszka** [comment]
Merged
