### ISSUE TITLE
Add what's changed + new contributors into btp-manager release notes

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#153]
**Description**

Right now release description is empty.

**AC**
- [x] 1) our release pipeline should create releases looking like: https://github.com/kyma-project/btp-manager/releases/tag/0.1.0

**Comment by MarekMichali** [comment]
> git log --pretty=format:"* %s by %an in [%h](https://github.com/kyma-project/btp-manager/commit/%h) " $(git describe --tags --abbrev=0 HEAD^)..HEAD > CHANGELOG.MD 

Gives a changelog between current and last release like this: 

>* Release pipeline, docs ```(#136)``` by Piotr Miśkiewicz in [199ccaf](https://github.com/kyma-project/btp-manager/commit/199ccaf) 

It is possible to click the commit hash but the plan is to replace the commit link with the PR link using something like this
> git log --pretty=format:"%h %s" main | grep <commit-hash> | grep -o " (#[0-9]\+)" | grep -o "[0-9]\+" | awk '{print "in https://github.com/kyma-project/btp-manager/pull/" $1}' > CHANGELOG.MD

**Comment by MarekMichali** [comment]
How it looks for now: https://github.com/MarekMichali/btp-manager/releases/tag/0.0.19.8

**Comment by MarekMichali** [comment]
Next version https://github.com/MarekMichali/btp-manager/releases/tag/0.0.20.1

**Comment by MarekMichali** [comment]
After discussion with @PK85 
- [ ] Full changelog should only show changes since last release
- [ ] Extract to script

**Comment by MarekMichali** [comment]
See #204
