### ISSUE TITLE
Add description to PR when promoting btp-manager to kyma

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#154]
**Description**

Right now when we promote btp-manager into kyma, the PR has an empty description.

**AC**
- [x] 1) Put a link to the btp-manager release page, like: https://github.com/kyma-project/btp-manager/releases/tag/0.1.0

**Comment by wozniakjan** [comment]
so this will just piggyback on release notes generated by https://github.com/kyma-project/btp-manager/issues/153, correct?
