### ISSUE TITLE
Set RBAC roles into resource we need to have access to

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#172]
**Description**

Right now we use wildcards, see: https://github.com/kyma-project/btp-manager/pull/123/files
We must have access only to the resources that we need.

**AC**
- [x] 1) set btp-manager RBAC ac roles to specific resources we need
- [x] 2) automate RBAC check when getting new chart from upstream, [see](https://github.com/kyma-project/btp-manager/blob/main/.github/workflows/auto-update.yml)
- [x] 3) find a way how to managed RBACs when some k8s types are gone from previous BTP Operator release and new BTP Operator release has some new k8s types to be created.
- [x] 4) enhance documentation about auto-update, [here](https://github.com/kyma-project/btp-manager/blob/main/docs/workflows.md#auto-update-chart-and-resources)

**Comment by wozniakjan** [comment]
I missed the docs part
