### ISSUE TITLE
When BTPOperator resource is in deletion phase ask user to delete service instances and bindings/secrets as default behavior

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#174]
**Description**

Default de-provisioning behavior must ask user to delete BTP Operator resources like `serviceinstances` and `servicebindings` (including secrets). That means disabling module means uninstalling everything created by that module by anyone. 

We still want to offer to user full delete which is implemented by our hard and soft delete phases.

**Reason**

Someone could disable the module for some reason and then needs to decide by himself what to do with existing instances and bindings. For example, the Connectivity Proxy module was enabled (which means a service connectivity instance was created), and then users disabled the BTPOperator module.

**AC**

- [x] 0) When user deletes  BTPOperator CR then reject that with proper message if SIs and/or SBs exist.
- [x] 1) Implement this feature and adjust [documentation](https://github.com/kyma-project/btp-manager/blob/main/docs/operations.md#deprovisioning)
- [x] 2) Optional full removal option should be triggered by labeling the resource with some kind of flag and then deleting an object.

**Comment by PK85** [comment]
Another possibilities how to handle deprovisioning:
- 1) when any SI or SB exist, list it to user and fail deprovisioning. Do nothing, ask user to delete them.

**Comment by piotrmiskiewicz** [comment]
PR: https://github.com/kyma-project/btp-manager/pull/208

**Comment by PK85** [comment]
@piotrmiskiewicz 
Review finding:
-create BTPOperator CR, create SI
- delete BTPOperator CR
- check status BTPOperator CR, should be SI block deletion
- add label force-delete true to BTPOperator CR
- check status BTPOperator CR, should be Hard delete

**Comment by szwedm** [comment]
PRs with feature implementation have been merged:
https://github.com/kyma-project/btp-manager/pull/208
https://github.com/kyma-project/btp-manager/pull/229
Closing the issue.
