### ISSUE TITLE
Create docs which describe how btp-manager works after dropping the dependency to module-manager

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#175]
Documentation is not up to date after recent changes to [provisioning](https://github.com/kyma-project/btp-manager/pull/98) and [update](https://github.com/kyma-project/btp-manager/pull/166) processes.
https://github.com/kyma-project/btp-manager/blob/main/docs/operations.md

**Comment by szwedm** [comment]
PR with docs updates: https://github.com/kyma-project/btp-manager/pull/182
