### ISSUE TITLE
Refactor module deprovisioning in btp-manager

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#186]
Currently the deprovisioning process in btp-manager relies on the GroupVersionKinds found in the chart:
https://github.com/kyma-project/btp-manager/blob/main/controllers/btpoperator_controller.go#L768
We can refactor it to delete applied resources from `module-resources/apply`

**Comment by szwedm** [comment]
PR: https://github.com/kyma-project/btp-manager/pull/193

**Comment by szwedm** [comment]
PR with addition of the outdated resources deprovisioning: https://github.com/kyma-project/btp-manager/pull/201
