### ISSUE TITLE
BTP-Manager final tests with Lifecycle Manager on dev Environment

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#187]
- [x] 1) promote our ~0.2.0~ newest BTP Manager version into the ```fast``` channel
- [x] 2) install BTP Manager on SKR on the preview plan
- [x] 3) install BTP Manager on SKR on a regular plan
- [x] 4) document the results of testing in the comment. Then out of that, we will see if we should create some tests or leave it to the neighbors - continued @PK85
- [x] 5) Test activation and disabling modules with Kyma CLI

**Comment by ralikio** [comment]
Notes:
1. Modules definition: https://github.com/kyma-project/kyma/tree/main/modules

**Comment by ralikio** [comment]
TODO: 
- Activate module with Kyma Cli
