### ISSUE TITLE
Review PRs with btp-oprator 0.3.8 bump

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#194]
- https://github.com/kyma-project/btp-manager/pull/184
- https://github.com/kyma-project/btp-manager/pull/192

**Comment by PK85** [comment]
@szwedm we have already 0.3.9 PR and tests have failed

**Comment by szwedm** [comment]
I adjusted the chart and manifests. Tests passed, bot is required to sign CLA before PR can be merged.

**Comment by szwedm** [comment]
PR: https://github.com/kyma-project/btp-manager/pull/196
