### ISSUE TITLE
Add unit and e2e test to the release process

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#198]
**Description**

We need to fail release if unit or e2e test are red.

**AC**
- [x] 1) improve our release pipeline, [see](https://github.com/kyma-project/btp-manager/actions/runs/4131773545/workflow) to start unit tests before other jobs. If fails do not trigger other jobs
- [x] 2) improve our release pipeline, [see](https://github.com/kyma-project/btp-manager/actions/runs/4131773545/workflow)  to start e2e test after images are present.
- [x] 3) refactor our workflow and make sure we do not have duplications jobs/steps. Reuse them across workflows, [see](https://docs.github.com/en/actions/using-workflows/reusing-workflows)
- [x] 4) check and if needed update testing and release documentation

**Comment by jaroslaw-pieszka** [comment]
https://github.com/kyma-project/btp-manager/pull/202

**Comment by jaroslaw-pieszka** [comment]
To be demoed on Iteration Review.
