### ISSUE TITLE
Exclude pre-delete-job by default when new PR with operator release

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#199]
**Description**

Improve generating module-resource with some chart resource exclusions. 

**AC**
- [x] 1) provide a way how to disable given chart resources (e.g. pre-delete-job) that will be not taken into account for module-resources directory
- [x] 2) regenerating local module-resources should as well exclude disabled resources
- [x] 3) allow to adjust configuration without code change 
- [x] 4) Document a feature: https://github.com/kyma-project/btp-manager/blob/main/docs/workflows.md#auto-update-chart-and-resources

**Comment by piotrmiskiewicz** [comment]
PR: https://github.com/kyma-project/btp-manager/pull/223/files

**Comment by szwedm** [comment]
PR with the requested feature has been merged:
https://github.com/kyma-project/btp-manager/pull/223
Closing the issue.
