### ISSUE TITLE
BTP-Operator gets READY without checking deployment status

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#216]
Issue:
- When installing btp-operator custom resource it's marked as ready, but SAP btp controller is still under installation.

Expected result:
- CR gets READY status only when deployment is READY

Same with the uninstallation process. Never delete BTP Operator resource if still controller deployment is present.

TODO:
- check deployment status instead of just checking if deployment exists,
- the module is ready only when deployment is ready

**Comment by szwedm** [comment]
PR: https://github.com/kyma-project/btp-manager/pull/265
