### ISSUE TITLE
BTP Manager template.yaml must be `target: remote`

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#219]
When we generate the template.yaml we have:

```
spec:
  target: control-plane
```
With LM installed out of Kyma, then LM tries to install BTM Manager in the kcp environment.

Expected spec:
```
spec:
  target: remote
```

`kyma alpha create module` command accepts a param to choose the target:
https://github.com/kyma-project/btp-manager/blob/main/Makefile#L145

TODO:
- when releasing existing template.yaml should contain `target:remote` (default)
- when releasing additional template template_control_plane.yaml, it should contain `target:control-plane`

**Comment by MarekMichali** [comment]
See #239

**Comment by PK85** [comment]
@MarekMichali just change the target
