### ISSUE TITLE
E2E test must create BTP Operator resource

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#225]
**Description**
E2E Test runs with dummy btp-operator creds on PR. And then for the release pipeline use real creds from prod.

TODO:
- [x] 1) create BTP Operator resource in the e2e test, check status (PR + release pipelines)
- [x] 2) in the release run it should provision real service instances like an audit-log class in the BTP Service Manager, check SI status (only release pipeline)
- [x] 3) Create service binding and check status (only release pipeline)
- [x] 4) Delete SI and SB, check if no SI/SB (only release pipeline)
- [x] 5) Persists credentials in the GitHub actions (check the best way of doing that) (only release pipeline)

**Comment by tillknuesting** [comment]
I think the issue is that it was not wanted to store any secrets in Github, as Kyma uses Secret Manager (Google Cloud) to store all credentials.

In my opinion the best way to at least partly overcome this is to use Google Cloud Workload Identity Federation. https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions https://github.com/google-github-actions/auth

**Comment by PK85** [comment]
@tillknuesting We are allowed now to do that :)  thanks for your suggestion.

**Comment by jaroslaw-pieszka** [comment]
WIP: https://github.com/kyma-project/btp-manager/pull/270

**Comment by jaroslaw-pieszka** [comment]
Additional features:
- [ ] download latests `smctl` command
- [ ] use smctl to remove service instances and service bindings (test tear down)
- [ ] consider usage of `smctl` to assert proper SI and SB state (for PR we use dummy credentials)
- [ ] SI and SB names should be unique

**Comment by jaroslaw-pieszka** [comment]
Documentation update: https://github.com/kyma-project/btp-manager/pull/282

**Comment by jaroslaw-pieszka** [comment]
Docs update WIP: https://github.com/kyma-project/btp-manager/pull/293

**Comment by jaroslaw-pieszka** [comment]
Internal documentation update: https://github.tools.sap/kyma/documentation/pull/299
