### ISSUE TITLE
React on SI/SB removals and reconcile BTP Operator CR

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#228]
**AC**:
- when the user removes SI/SB then immediately reconcile BTP Operator CR

**Comment by PK85** [comment]
See:
- https://github.com/kubernetes-sigs/controller-runtime/issues/540
- https://github.com/kubernetes-sigs/controller-runtime/pull/2159

**Comment by szwedm** [comment]
@piotrmiskiewicz we can decrease reconciliation interval from 15 mins to 3 mins

**Comment by piotrmiskiewicz** [comment]
PR: https://github.com/kyma-project/btp-manager/pull/240
