### ISSUE TITLE
DeleteOptions kind bug

### ISSUE THREAD

**Issue by ukff** [kyma-project/btp-manager#23]
1. switch to "deprovisioning-debug" branch
2. run app in /operator
3. ensure that "Install Complete!! Happy Manifesting!" is be printed out
4. ensure you are connected to k3d-dem config (should be done automatically)
5. type "k delete btpoperator btpoperator"
6. observe error in "btpoperator_controller.go" on line 411
	"no kind "DeleteOptions" is registered for version "admissionregistration.k8s.io/v1" in scheme "k8s.io/apimachinery@v1.23.8-k3s1/pkg/runtime/scheme.go:100""

**Comment by wozniakjan** [comment]
crossplane had similar issue with sigs.k8s.io/controller-runtime scheme - https://github.com/crossplane/crossplane/pull/2285.

`DeleteOptions` are part of metav1 https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/delete-options/, I'm curious if it's worth creating new schema and then registering all from client go as done in
https://github.com/kyma-project/btp-manager/blob/ad505688bfe2013bab97bbc15500ba1952e49063/operator/main.go#L41-L49

given there is [exported client-go scheme](https://github.com/kubernetes/client-go/blob/0d5739633518230d2b2b8d5378aef126db5aacc3/kubernetes/scheme/register.go#L77) that already has the native kubernetes types registered. The `sample-controller` has a pattern of [using it that way](https://github.com/kubernetes/sample-controller/blob/e01c4e0640862ccc38580bc32ef22afc0ecc329b/controller.go#L97)

**Comment by tillknuesting** [comment]
solved

**Comment by wozniakjan** [comment]
yeah, weird, @ukff confirmed it's no longer throwing error for deletions.

Replacing this:
```
scheme   = runtime.NewScheme() 
utilruntime.Must(clientgoscheme.AddToScheme(scheme))
...
Client: mgr.GetClient(),
```
with using client-go scheme everywhere
```
scheme = clientgoscheme.Scheme
...
Client: scheme,
```
seems to have done the trick. My guess would be the controller-runtime had some regression with scheme handling
