### ISSUE TITLE
Adjust promotion pipeline to create PR in the https://github.tools.sap/kyma/kyma-modules

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#243]
**AC**
- [x] 1) switch to the new repository: https://github.tools.sap/kyma/kyma-modules
- [x] 2) pipeline input param channel should have only two options: fast and regular
- [x] 3) when the given channel is selected then adjust resource name (example for fast)
  - [x] a) ```metadata:
  name: btp-operator-fast```
  - [x] b)   ```spec:
  channel: fast```
- [x] 4) for regular: ```metadata:
  name: btp-operator-regular``` and ```spec:
  channel: regular```
- [x] 5) add always this annotation: ```  annotations:
    "operator.kyma-project.io/doc-url": "https://github.com/kyma-project/btp-manager"```
 
If we need a new technical user this could be needed: https://technical-user-management.github.tools.sap/

**Comment by piotrmiskiewicz** [comment]
1. Created application in github tools, see: https://wiki.one.int.sap/wiki/display/CLMAM/How+to+manage+Jenkins+with+CAM+using+GitHub
