### ISSUE TITLE
Auto update chart/resources GA failing to create an item in gophers board

### ISSUE THREAD

**Issue by MarekMichali** [kyma-project/btp-manager#249]
**Description**

[kyma-btp-manager-bot](https://github.com/kyma-btp-manager-bot) creates a PR with new updates, but no new item is created in the TODO column. The `Auto update chart/resources` GA returns an [error](https://github.com/kyma-project/btp-manager/actions/runs/4549349707/jobs/8021332601)

> gh: Your token has not been granted the required scopes to execute this query. The 'addProjectV2ItemById' field requires one of the following scopes: ['project'], but your token has only been granted the: ['repo'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
> Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['repo'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
> Error: Process completed with exit code 1.

Jan left a [comment](https://github.com/kyma-project/btp-manager/pull/203) that the bot may be missing some priviliges. 

**AC**

* When the bot creates a PR, an item should be created from it on the gophers board in the TODO column

**Comment by jaroslaw-pieszka** [comment]
Token updated with required access rights. Needs to be tested.

**Comment by jaroslaw-pieszka** [comment]
Token updated with required permissions.
