### ISSUE TITLE
Provide E2E upgrade test between two latest releases

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#260]
**Description**

When doing a release we need to run an E2E upgrade test.

**AC**
- [x] 1)  Install the previously released version and check if the installation works
- [x] 2) Use proper credentials and install audit log instance and binding
- [x] 3) Upgrade to the new release and check if the installation works
- [x] 4) Add new service binding to the audit log instance, check the status
- [x] 5) Delete bindings and instance, checks if no SI/ SB resources
- [x] 6) Describe E2E upgrade tests in our documentation

This ticket handles how to use proper creds: https://github.com/kyma-project/btp-manager/issues/225

**Comment by szwedm** [comment]
E2E tests workflow runs:
https://github.com/kyma-project/btp-manager/actions/runs/5045180572
