### ISSUE TITLE
Failing run-e2e-test

### ISSUE THREAD

**Issue by MarekMichali** [kyma-project/btp-manager#273]
The value found in manifest.json `"mediaType: "application/gzip"` for CustomResourceDefinition changed to `"application/octet-stream`. This caused the `run-e2e-test` pipeline to [fail](https://github.com/kyma-project/btp-manager/actions/runs/4807608875/jobs/8556689080) because we are looking for the type [`application/gzip`](https://github.com/kyma-project/btp-manager/blob/6e4a55e174ef09ad5c91d4f2f29cc5f7c13e9063/scripts/run_module_image.sh#L37). The pipeline should be able to handle the old and new mediaType

The idea is to add a mediaType check and add an alternative path if no `mediaType: "application/gzip"` is detected. We could use `jq` to check this, and then also to detect the rendered.yaml file containing `kind: CustomResourceDefinition` for the alternative path.

**Comment by jaroslaw-pieszka** [comment]
Could we consider extracting this logic to separate script?

**Comment by MarekMichali** [comment]
We have determined that we are getting raw kubernetes yaml and need to add support for such a scenario to fix the test.
