### ISSUE TITLE
Adjust State for missing secret reason

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#275]
**Description**

The decision was made that if some dependencies are missing for a given module then we need to set the proper state, details and depends on: https://github.com/kyma-project/lifecycle-manager/issues/525

**AC**

- [x] 1) Adjust a State from "Error" to a new state "Warning", adjust test and documentation
- [x] 2) Merge to btp-manager when LM has it implemented and deployed to environments

**Comment by PK85** [comment]
now:
```
16	Error	Ready	false	InvalidSecret	sap-btp-manager secret does not contain required data - create proper secret
17	Error	Ready	false	MissingSecret	sap-btp-manager secret was not found - create proper secret
```

After:
```
16	Error	Ready	false	InvalidSecret	sap-btp-manager secret does not contain required data - create proper secret
17	Warning	Ready	false	MissingSecret	sap-btp-manager secret was not found - create proper secret
```

**Comment by piotrmiskiewicz** [comment]
example promotion PR: https://github.tools.sap/kyma/kyma-modules/pull/107
