### ISSUE TITLE
Prepare customer-facing documentation for BTP Manager

### ISSUE THREAD

**Issue by IwonaLanger** [kyma-project/btp-manager#290]
**Description**
For the new modular approach, we need documentation that is common for all the modules, e.g. general description (landing page), getting started, module configuration, etc.

**AC**
- [x] Your audience is the end-user so the documentation must be written for them (not for the team that builds this module, or other SAP teams that wish to build a module, not for SRE, etc). Remember the context and how much the user knows by now (probably just high-level knowledge about Kyma as a whole and that there are modules).
- [x] The documentation must be consumable by the kyma-project.io home page (split into several information types/md files) - no acceptance criteria for this point specified
- [x] Create a docs folder following the standard structure proposed in -> ~[this issue](https://github.com/kyma-project/kyma/issues/16775)~ [this decision record](https://github.tools.sap/kyma/community/issues/180)
- [x] In each module's documentation include:
  - [x]  General description of the functionality (~if the module is mandatory, mention it!~)
  - [x]  Getting Started - instructions on how to [enable](https://github.com/kyma-project/community/issues/792) and use the module. ~The module docs must mention the prerequisite that the module must be enabled (don't explain 'how', just link to the generic document we (will) have on how to enable modules in Kyma (see [Adjust the Get Started docs to modular approach](https://github.com/kyma-project/kyma/issues/16778))~
  - [x] Module configuration
  - [x] Instructional documents (currently called "dev tutorials" and "operational guides") - must be isolated, i.e. no dependencies on other tutorials or modules. An example.
  -  ~If needed, troubleshooting~ Not needed for now
  -  ~the link to instructions on how to give feedback~ the instructions only available on the website

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by IwonaLanger** [comment]
[Adjust BTP Manager docs to the new documentation requirements #317](https://github.com/kyma-project/btp-manager/pull/317)

**Comment by ralikio** [comment]
Linked PR #317
