### ISSUE TITLE
Support error messages in the btp-operator CR

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#30]
**Description**

Besides only stating: ERROR and READY we need to inform the user what went wrong.

**Acceptance Criteria**

1. - [x] Collect and document all error types during provisioning/deprovisioning and document them properly
2. - [x] Implement in the BtpOperator Custom Resource details about errors, like message, reason etc
3. - [x] Enhance tests to check all of those states

**Comment by jaroslaw-pieszka** [comment]
Initial proposal:

<div style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; direction: ltr;">

Case | Type | Status | Reason | Message
-- | -- | -- | -- | --
No secret | Ready | False | Cannot get secret | Secret resource not found
  |   |   |   | Other failure while getting secret
Secret verification failed | Ready | False | Invalid secret | Keys missing
  |   |   |   | Values missing
  |   |   |   | Keys and values missing
Deprovisioning failed | Deprovisioned | False | Failed to remove resources | Failed to remove resources
  |   |   |   | Removal timeouted
  | Deprovisioned | False | Soft delete failed | Soft deletion of bindings failed
  |   |   |   | Bindings still exits
  |   |   |   | Soft deletion of instance failed
  |   |   |   | Instances still exits
  |   |   |   | Failed to remove related installed resources
  | Deprovisioned | False | Hard delete failed | While deleting all resources
Reconciling failed | Reconciled | False | Unable to fetch BTPOperators | Unable to fetch BTPOperators
  |   |   | Unable to fetch BTPOperator resources | Unable to fetch BTPOperator resources
Setting state failed | StateUpdated | False | Cannot get secret | Failed to get required secret
  |   |   | Invalid secret | Keys missing
  |   |   |   | Values missing
  |   |   |   | Keys and values missing

</div>

**Comment by jaroslaw-pieszka** [comment]
Second iteration:
<div style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; direction: ltr;">

Phase | Case | Timespan | Type | Status | Reason | Message
-- | -- | -- | -- | -- | -- | --
Provisioning/Reconciling | All went well | S | Ready | True | InitialState | TBD
Provisioning/Reconciling | Processing | M | Ready | True | Processing | Processing chart
Provisioning/Reconciling | Checking | M | Ready | True | Processing | Checking consistency
Provisioning/Reconciling | This is not the oldest BtpOperator CR | L | Ready | False | OlderCRExists | <name> BtpOperator CR in <namespace> reconciles the operand
Provisioning/Reconciling |   | L | Ready | False | MissingSecret | Secret resource not found
Provisioning/Reconciling |   | L | Ready | False | MissingSecret | Other failure while getting secret
Provisioning/Reconciling | Secret verification failed | L | Ready | False | InvalidSecret | Keys missing
Provisioning/Reconciling |   | L | Ready | False | InvalidSecret | Values missing
Provisioning/Reconciling |   | L | Ready | False | InvalidSecret | Keys and values missing
Deprovisioning | Hard delete started | M | Ready | False | HardDeleting | Hard deleting of resources started
Deprovisioning | Hard delete failed | S | Ready | False | HardDeleteFailed | Failed to remove resources
Deprovisioning | Hard delete failed | S | Ready | False | HardDeleteFailed | Removal timeouted
Deprovisioning | Soft delete started | M | Ready | False | SoftDeleting | Soft deletion of resources started
Deprovisioning | Soft deleting bindings failed | L | Ready | False | SoftDeleteFailed | Soft deletion of bindings failed
Deprovisioning | Soft deleting bindings failed | L | Ready | False | SoftDeleteFailed | Bindings still exits
Deprovisioning | Soft deleting instances failed | L | Ready | False | SoftDeleteFailed | Soft deletion of instance failed
Deprovisioning | Soft deleting instances failed | L | Ready | False | SoftDeleteFailed | Instances still exits
Deprovisioning | Soft delete failed | L | Ready | False | SoftDeleteFailed | Failed to remove related installed resources

</div>

**Comment by jaroslaw-pieszka** [comment]
Draft https://github.com/kyma-project/btp-manager/pull/37 - test being implemented

**Comment by jaroslaw-pieszka** [comment]
finał


No. | CR state | Condition type | Condition status | Condition reason | Remark
-- | -- | -- | -- | -- | --
1 | Ready | Ready | True | ReconcileSucceeded | Reconciled successfully
2 | Processing | Ready | True | Recovered | Recovered from error
3 | Processing | Ready | False | Initialized | Initial processing or chart is inconsistent
4 | Processing | Ready | False | Processing | Final state after deprovisioning
5 | Deleting | Ready | False | HardDeleting | Trying to hard delete
6 | Deleting | Ready | False | SoftDeleting | Trying to soft delete after hard delete failed
7 | Error | Ready | False | OlderCRExists | This CR is not the oldest one so does not represent the module status
8 | Error | Ready | False | MissingSecret | 'sap-btp-manager' secret was not found - create proper secret
9 | Error | Ready | False | InvalidSecret | 'sap-btp-manager' secret do not contain required data - create proper secret
10 | Error | Ready | False | ResourceRemovalFailed | Some resources could be left due to errors while deprovisiong
11 | Error | Ready | False | ChartInstallFailed | Failure during chart installation
12 | Error | Ready | False | ConsistencyCheckFailed | Failure during consistency check

**Comment by szwedm** [comment]
PR with the requested feature was merged to main:
https://github.com/kyma-project/btp-manager/pull/37
Closing the issue.

**Comment by szwedm** [comment]
Up to date docs:
https://github.com/kyma-project/btp-manager/blob/main/docs/operations.md
