### ISSUE TITLE
Introduce input config map for btp-manager configuration

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#31]
**Description**

During one of our sprint reviews, there was no way to reconfigure reconciliation parameters without rebuilding the application. This ticket is about to do that without that.

**Acceptance Criteria**

0. - [ ] define a number of configurations that are worth to be set from outside and get a review from the team (e.g.  reconciliation interval time etc.)
1. - [ ] Introduce a way (for example by config map) from where btp-manager can be reconfigured. Rebuild and redeploy should be not required
2. - [ ] If config map does not exist, take defaults from the code
3. - [ ] document all possible input configurations

**Comment by wozniakjan** [comment]
afaik, currently the lowest maintenance and almost instant propagation of changes can be achieved via CLI flags / env variables directly put on the `Deployment`. However, this comes with a pod restart.

Using `ConfigMaps` has two modes, both are not issues free
- as mount - eventually propagated but not deterministic and can be slow https://github.com/kubernetes/kubernetes/issues/30189
- as env - not automatically propagated, requires trigger of pod restart https://github.com/kubernetes/kubernetes/issues/22368

**Comment by wozniakjan** [comment]
after discussion with @PK85, it should be third alternative
- watch kube-api on the specific `ConfigMap` and live propagate changes to the controller config knobs
