### ISSUE TITLE
Auto bump btp-manager version in kyma

### ISSUE THREAD

**Issue by MarekMichali** [kyma-project/btp-manager#321]
**Description**

The release of a new version of btp-manager requires a manual bump in the kyma repository https://github.com/kyma-project/kyma/pull/17635. We could automate this by adding, for example, an additional step in the `Promote to channel` workflow.

**AC**

- [ ] Automate the bump of btp-manager in kyma repository

**Comment by PK85** [comment]
We will soon start to use new way of how security will be monitored. Closing this ticket.
