### ISSUE TITLE
BTP Manager - Metrics v2

### ISSUE THREAD

**Issue by ukff** [kyma-project/btp-manager#334]
**AC**
- [x] 1) Create Documentation
  - [x] 1.1) In open source describe metrics that are exposed by btp-manager deployment itself
  - [x] 1.2) on-call documents (describe where to find our grafana dashboard, what's the name of that)
- [x] 2) Metrics from Kube metrics (Landscape panel view)
   - [x] 2.1) sap-btp-manager ConfigMaps Count - monitor changes of ConfigMap that store configuration for a BTP Manager, check the existence of the map. Number of events that designate secrets modifications
     - [x] Add also for selected shoot 
   - [x] 2.2) Force Delete Count - number of manager instances with BtpOperator CRD labeled by "force-delete"- the metric tells if there were any external modifications done to the resource 
     - [x] Add also for selected shoot  
   - [x] 2.3) besides the number of deployments of the btp-manager, display the number of deployments of the sap-btp operator
   - [x] 2.4) Number of shoots per Service Instance Range
     - 0 Instances
     - 1-5 Instances
     - 6-15 Instances
     - 16-30 Instances
     - 31-50 Instances
     - more than 50 Instances
   - [x] 2.5) Number of shoots per Service Binding Range
     - 0 Bindings
     - 1-5 Bindings
     - 6-15 Bindings
     - 16-30 Bindings
     - 31-50 Bindings
     - more than 50 Bindings
   - [x] 2.5) Update RMA ConfigMap with Grafana Json Dashboard
- [x] 3) Metrics from BTP Manager Service Metrics (BTP Manager Service Metrics panel view) (in selected time period)
  - kubebuilder metrics:
    - [x] 3.1)  Reconciliation Success
    - [x] 3.2) Reconciliation Error
    - [x] 3.3) Reconciliation Duration
    - [x] 3.4) Reconciliation Invocation Count
    - [x] 3.5) Update RMA ConfigMap with Grafana Json Dashboard
  - custom metrics:
    - [x] 3.6) Certs Regenerations Count - BTP Manager Cert regenerations
- [x] 4) Grafana View modifications:
  - [x] 4.1) Add filter values to all panels `Titles`; `shootID` and `btpOperator CR name`
  - [x] 4.2) Rename `Uknown` status to `Unrecognized`
  - [x] 4.3) Rebame `None` status to `Empty`

### Other ideas - to be discussed

- [ ] Routines Count - Go Routine Start/Finish (this is about goroutines created by BTP manager itself, kubebuilder routines will be filtered out)
- [ ] Hard/Soft Removal - number of soft-delete/hard-delete operations - tells how many times SI/SB finalizers were removed (Soft delete way)
- [ ] No status on BTP Operator CR from reconciler
- [ ] ~~Applied Resources - count resourcesToApply invocations, mainly for logging resources, go routine invocations -  in the method we are invoking as many go routines as there are resources to apply (see resourcesToApply and resourcesToApply).~~
- [ ] ~~Top ten usages of instances and bindings.~~
- [ ] ~~Info when metrics components are not working (empty graph)~~

### Additionally, we have discussed key points and practices that we want to remember about while implementing the metrics:

	• Kubebuilder metrics for both of our managers, main one and the helper
	• For how long a metric stays in Grafana and if RMA removes shoots from Grafana for removed runtimes.
	• Do not make external calls, e.g. do not call K8S api to check Kyma Resource
        • Use Colors for Metrics so that we can quickly see that we need to do something
        • Round numbers
	• Lets be descriptive
	• Lets keep meeting!

**Comment by MarekMichali** [comment]
PR: https://github.tools.sap/kyma/management-plane-config/pull/3895

**Comment by MarekMichali** [comment]
PR's in BTP Manager:
https://github.com/kyma-project/btp-manager/pull/370
https://github.com/kyma-project/btp-manager/pull/374
https://github.com/kyma-project/btp-manager/pull/376
