### ISSUE TITLE
Multiple BtpOperator CRs restore scenario doesn't work

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#335]
**Description**
We see some BTP Manager instances have one BtpOperator CR instance in the Error/OlderCRExists. Then after around 10h this was finally reconciled and it went into the Ready state as expected.

**AC**
- [x] 1) Write a unit test that proves that we have one BtpOperator CR with state OlderCRExists
- [x] 2) Find and place which causes an issue and fix it
- [x] ~~3) Consider using global SyncPeriod, to avoid such issues in the future~~ Use reconcile.Result instead.

**Comment by szwedm** [comment]
PR: https://github.com/kyma-project/btp-manager/pull/342
