### ISSUE TITLE
On Pull Request test new changes on k3d cluster

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#34]
**Description**
 
Right now we just have a simple check under PR. Which is build and unit tests. This task is about providing integration tests.

**Acceptance Criteria**

1. - [x]  create a pipeline that tests btp-manager provisioning and de-provisioning on k3d
2. - [x] testing job on PR is not taking longer than 3 minutes total (ensure caching etc.)
3. - [ ] Add documentation about what we test and how

**Comment by PK85** [comment]
I've just checked, we need to build images at least from the main branch by prow. Then the rest of the testing etc could be github-action pipeline. And we cannot store any SAP creds in the github infrastructure.

**Comment by tillknuesting** [comment]
An end to end pipeline was added https://github.com/kyma-project/btp-manager/actions/workflows/e2e-test-k3s.yml that uses the container image build by pull-btp-manager-build. Also, in a separate test unit tests are executed. There is a follow-up ticket that works on the end 2 end test and pipeline. https://github.com/kyma-project/btp-manager/issues/47
