### ISSUE TITLE
Markdown link checker

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#375]
**Description**

Check all links existence in the MD files.

**AC**
- [ ] 1) Check and use `github-action-markdown-link-check` plugin, see: https://github.com/kyma-project/telemetry-manager/blob/0bfd5fc3f477a94c48e1d580f676ae439ec9c7b8/.github/workflows/markdown-link-check.yml
- [x] 2) double check with Torsten if he is ok to use it

**Comment by MarekMichali** [comment]
PR: https://github.com/kyma-project/btp-manager/pull/386

The job is configured to run on every PR. We may consider changing it to a periodic job to scan the entire repository daily.
