### ISSUE TITLE
Release workflow: check if btp-manager image is signed

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#396]
**Description**

Our GitHub actions release pipeline awaits given btp-manager image. This image is generated by prow pipeline which is as well signing images. It can happen that signing has failed but the image exist. We need to improve our GA release pipeline.

**AC**
- [x] 1) In the release pipeline beside the check of the image existence check as well if the image is signed.

**How to check if signed**
- ```dss -s https://signing.repositories.cloud.sap/ lookup europe-docker.pkg.dev/kyma-project/prod/btp-manager 0.4.9```
- https://pages.github.tools.sap/Repository-Services/Signify/how_to/download_cli/

**Comment by MarekMichali** [comment]
We could also use https://github.com/autotelic/action-wait-for-status-check as well. If the image is not signed, the prow job will fail even if the image was built. The action will detect that the job failed and we can block the release. [Example](https://github.com/kyma-project/istio/blob/e1862d5af45f630472eda1148cbc65b9bcc0b09f/.github/workflows/create-release.yaml#L58) use in other module repos:

**Comment by MarekMichali** [comment]
We check the commit status with the given name if it's successful. Thanks to this, we can switch in the future for any kind of jobs, we are not bound to prow.

**Comment by MarekMichali** [comment]
The `Validate release' now prints a warning if we created the artifacts in previous releases.<img width="568" alt="image" src="https://github.com/kyma-project/btp-manager/assets/56163696/f8359739-7356-4f9a-8396-413675553206">

The new step `Wait for prow jobs` checks the commit status if the given jobs were successful. In our case these are prow jobs, but it can be changed to any kind of job, we just pass the job name.
