### ISSUE TITLE
Magic label required by btp-manager is not transparent to the user

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/btp-manager#422]
**Description**
When you apply the sap-btp-manager secret without label `app.kubernetes.io/managed-by: kcp-kyma-environment-broker` the operator can't find it. It is not included in the helper script [create-secret-file.sh](https://github.com/kyma-project/btp-manager/blob/main/hack/create-secret-file.sh) and it is impossible to guess from operator logs. 
Please update the documentation and [the interactive tutorial](https://killercoda.com/kyma-project/scenario/btp-services)
The issue was introduced by #361

**Comment by PK85** [comment]
- the [create-secret-file.sh](https://github.com/kyma-project/btp-manager/blob/main/hack/create-secret-file.sh) script has been fixed 2 months ago (see: https://github.com/kyma-project/btp-manager/commit/cb4aaf8315e6524ed6293d12d6296fc361c626ea)
- docs describing a label: https://github.com/kyma-project/btp-manager/blob/1.0.0/docs/contributor/02-10-operations.md?plain=1#L47
