### ISSUE TITLE
Integrate Dependabot

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#435]
**Description**

This ticket is about adding dependabot to our repository.

**Reason**

To keep our dependencies always up to date.

**AC**
- [x] 1) Integrate dependabot to btp-manager repository
- [x] 2) When new PR created from dependabot and all tests are green, automerge. This PR should have a label `kind/enhancement`
- [ ] 3) Adjust documentation describing dependabot workflow

**Comment by piotrmiskiewicz** [comment]
PR: https://github.com/kyma-project/btp-manager/pull/447

**Comment by piotrmiskiewicz** [comment]
We decided to not approve automatically because we want to have a control all dependabot changes
We can decide later to have auto approve.

**Comment by piotrmiskiewicz** [comment]
there is nothing special to document

**Comment by ralikio** [comment]
Done.
