### ISSUE TITLE
Support BTP manager versioning and make chart always up to date

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#44]
**Description**

Right now we have something like that, see https://github.com/kyma-project/btp-manager/blob/main/charts/btp-manager/templates/apps_v1_deployment_btp-manager-controller-manager.yaml#L66:
- image: op-skr-registry.localhost:60765/unsigned/operator-images/btp-manager:0.0.1

Which points to not existing image. This task is to make that chart always up to date and the image should exist and be related to given PR etc.

**Acceptance Criteria**
- [x] 0) get knowledge how Module Manager install modules out of module template
- [x] 1) when PR is created, we need to have the PR version here: https://github.com/kyma-project/btp-manager/blob/main/charts/btp-manager/templates/apps_v1_deployment_btp-manager-controller-manager.yaml#L66
- [x] ~~2) when PR merged to main, we need to run pipeline/test (all tests including e2e one) from main, and if green bump version to commit version~~
- [x] 3) we need to have a way to create a release from main with versioning e.g. 0.1.0. [Optional requirement: When the release is created and green we can update the BTP Manager module template with that version for all environments]
- [x] 4) document release process

**Comment by piotrmiskiewicz** [comment]
Module templates must be added here: https://github.com/kyma-project/kyma/tree/main/modules
See PR for Keda module: https://github.com/kyma-project/kyma/pull/16193

**Comment by PK85** [comment]
@piotrmiskiewicz comment about my acceptance criteria, I'd like to have a solution where when we create PR we can use new image and test it via chart installation. Take it into consideration. That means every PR change, new commit, we run test against that new image.

**Comment by PK85** [comment]
@piotrmiskiewicz I just crossed out AC nr 2. After 1) we will have PR-xxx images in main, and then when 3) we will release and test sem versioned image.

**Comment by PK85** [comment]
Meeting PK and @piotrmiskiewicz, outcome:
- release image name must equal the release tag (sem ver required)

**Comment by piotrmiskiewicz** [comment]
1. Remove chart from GIT (add to gitignore file)

**Comment by piotrmiskiewicz** [comment]
define a ticket with adding changelog
