### ISSUE TITLE
Update BTP Manager project structure and merge two make files into one

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#46]
**Description**

Module manager has only one make file, [see](https://github.com/kyma-project/module-manager). Update the project structure to that format. Example KEDA Manager adjustment, [here](https://github.com/kyma-project/keda-manager/pull/48/files)

**Acceptance Criteria**
1. - [x] Update project
2. - [x] Make sure all tests/pipelines works as expected

**Comment by szwedm** [comment]
PR:
https://github.com/kyma-project/btp-manager/pull/92
