### ISSUE TITLE
Implement e2e test on k3d

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#47]
**Description**

This task is to have e2e tests. We already have a place for them: https://github.com/kyma-project/btp-manager/blob/main/testing/go/e2e_test.go

**Acceptance Criteria**:
- [x] 1) write a test case where we use dummy secret (see: examples/btp-manager-secret.yaml) and deployments/prerequisites.yaml,  test scenarios:
  - [x] a) create BTPOperator resource, check status, check btp-operator-controller status, create dummy serviceInstace and check that it is in errorState (because of dummy credentials)
- [ ] 2) document and present how to stop pipeline during execution (stoping in given place in the test will be even better), login into k3d of the given run, and check resources statuses

**Comment by PK85** [comment]
@tillknuesting use yaml files as a testing data

**Comment by tillknuesting** [comment]
PR for the go test: https://github.com/kyma-project/btp-manager/pull/62

**Comment by tillknuesting** [comment]
This is the final PR for this ticket: https://github.com/kyma-project/btp-manager/pull/83

**Comment by tillknuesting** [comment]
Introducing SSH into Github Actions seems more complex as authentication is a big issue. This is still left todo for another person.
