### ISSUE TITLE
Execute btp-manager tests on many k8s versions at once

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#477]
**Description**

We are asked to test BTP-Manager on new k8s versions every month. We need to automate this process.

Info: right now SKRs run on k8s v1.26.

**AC**

- [x] 0) Check how to fetch k8s supported versions by k3s
- [x] 1)  Reuse pipeline where we run k3s and create matrix tests (investigate GA feature about that)
- [x] 2) Check if we run those matrix tests only when releasing or on PRs too (on both)
- [x] 3) General test execution must not take longer than without matrix tests
- [x] 4) Release - default 3, overridden by input parameters, last defined by minor version (not patch) 

**Expected result**
- We know that BTP Manager works on all new k8s versions.

**Info**
- https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Comment by jaroslaw-pieszka** [comment]
Matrix can be created dynamically as an output from one of previous jobs.

**Comment by jaroslaw-pieszka** [comment]
#488
