### ISSUE TITLE
Update btp-operator resources to the newest version regardless of the BtpOperator CR state

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#566]
**Reason**
We have a situation where the newest BTP Manager still operates with the old btp-operator version.

**AC**
- [x] 1) Write an e2e test proving the lack of upgrade (should we run it only when releasing or on every PR, right now e2e upgrade tests are executed only in the release pipeline)
- [x] 2) Improve reconciliation loop to upgrade always btp-operator if a new version is provided in the manager

**Comment by szwedm** [comment]
PR with e2e upgrade test: https://github.com/kyma-project/btp-manager/pull/591

**Comment by szwedm** [comment]
PR with reconciliation fix: https://github.com/kyma-project/btp-manager/pull/596
