### ISSUE TITLE
Speed up BTP Manager installation time

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#581]
**Description**

Generally, BTP Manager installation takes a lot of time, even some users reported 2 min to get BTPOperator in Ready status.

**Reason**

We use 4k rsabit KEY, which takes a lot of CPU and with 0,2 max CPU takes a lot of time.

**AC**

- [x] 1) check how many seconds it takes BTP Manager to be installed with a 1k rsabit key. It should take 1,2 sec for the BTP Manager and the same for the BTP Operator. Try to make the installation finished in around 5 seconds max.
- [x] 2) check if 0.2 CPU max limit is not a bottleneck. We could extend this as well.
- [x] 3) Check if BTP Manager regenerates certs when the existing running BTPManager with 4k key is upgraded to BTPManager with 1k.
- [x] 4) document under this ticket the exact reason for the long installation and what action was taken

**Comment by KsaweryZietara** [comment]
1. Reducing the rsabit key to 1k bits shortens installation time. A generation of self signed cert took 40 seconds less and generation of the signed webhook certificate took 27 seconds less.
2. 0.2 CPU max limit is not a bottleneck, increasing it does not shorten the installation time.
3. BTP Manager doesn't regenerates certs when the existing running BTPManager with 4k key is upgraded to BTPManager with 1k.
