### ISSUE TITLE
Review and Update SAP BTP Operator-related Content in Kyma Learning Journey

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/btp-manager#651]
**Description**

[Delivering Side-by-Side Extensibility based on SAP BTP, Kyma runtime](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime) Kyma Learning Journey got outdated. Markus Haug would like to cooperate with us in updating it.

For the SAP BTP Operator module, we need to take care of the following items:

- [x] [Defining SAP BTP Service Management in the Kyma Environment](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/defining-sap-btp-service-management-in-the-kyma-environment_a2d02cae-3e38-4297-83e6-8f388f609889)
- [x] [Setting Up a Service Instance and a Service Binding on the SAP BTP, Kyma Runtime](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/setting-up-a-service-instance-and-a-service-binding-on-the-sap-btp-kyma-runtime_c850f27a-5f24-40b6-93ba-b044cf3eac12)

**Reasons**

Content update requiring cross-team collaboration.

**Assignees**

@kyma-project/technical-writers
@PK85 

**Attachments**

See #5292 in internal /backlog

**Comment by IwonaLanger** [comment]
[PR]( https://github.tools.sap/SAP-BTP-Courses/KYM400_Content/pull/37)

**Comment by IwonaLanger** [comment]
Markus Haug merged the PR.
