### ISSUE TITLE
Make our suite_test configurable to run on real cluster (option) and mandatory verbose logs for tests that succceded

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#70]
Size: S

**Describe**

Enhance our testing suite to see more for regular runs and be able to run in on k3s or any other local cluster.

**AC**
- 1) make Gingo verbose by default (that will present controller logs from every test, test time execution, order, etc) + support runs by labels
```   
   suiteCfg, reporterCfg := GinkgoConfiguration()
   suiteCfg.LabelFilter = $TEST_LABELS
   reporterCfg.Verbose = true
   RunSpecs(t, "Controller Suite", suiteCfg, reporterCfg)
```
  - way to mark test with label/labels  ```When("update of all resources names and bump chart version", Label("test-update", "jarek"), func() {)```
  
- 2) prepare a script (e.g. create a dir for testing utils ) which allows to set the below environment variables + create a testing option section in the documentation
  - "KUBEBUILDER_ASSETS", "../bin/k8s/1.25.0-darwin-arm64")
  - "USE_EXISTING_CLUSTER", "true")
  - "TEST_LABELS"=(test_jarka, dupa)

**Comment by jaroslaw-pieszka** [comment]
Draft: https://github.com/kyma-project/btp-manager/pull/93

**Comment by jaroslaw-pieszka** [comment]
Revised after discussion with @PK85. Script sets the envs that are used by CLI (via make). Using IDE you can set variables in Run Configuration (assuming Goland).
