### ISSUE TITLE
BTP-Manager: Gophers do a pilot with new GA to create images from neighbours

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#718]
**Description**

Prow will be down soon and neighbours team prepared a new GA jobs that will create and sign images. This task is about enabling that on PR level and release level in the BTP-Manager and check if it works.

When those new steps will not work it must no harm PRs and releases.

**AC**
- [x] 1) Enable as optional step on PR level (add some sufix to the image version)
- [x] 2) Enable as optional step on Release level (add some sufix to the image version)
- [x] 3) Document path how to switch from prow to GA

**Comment by piotrmiskiewicz** [comment]
Docs available on PR: https://github.com/kyma-project/test-infra/pull/10983

**Comment by MarekMichali** [comment]
To enable this on release we need to wait for https://github.com/kyma-project/test-infra/issues/10987.

**Comment by MarekMichali** [comment]
To switch on PR's from prow to GA: 
* remove the `/ga` from image name https://github.com/kyma-project/btp-manager/blob/cf0417ba00a41cef0ee4d5d78c36b2e170629ed0/.github/workflows/pull-btp-manager-build-ga.yaml#L15
* Remove the build job from prow
* Adjust the name of this workflow job to be without the `-ga` suffix https://github.com/kyma-project/btp-manager/blob/cf0417ba00a41cef0ee4d5d78c36b2e170629ed0/.github/workflows/pull-btp-manager-build-ga.yaml#L1
* Replace the content of the `Dockerfile` with the content from `Dockerfile.ga`. Remove the `Dockerfile.ga` from repo. Change the `Dockerfile.ga` name in workflow to `Dockerfile` https://github.com/kyma-project/btp-manager/blob/cf0417ba00a41cef0ee4d5d78c36b2e170629ed0/.github/workflows/pull-btp-manager-build-ga.yaml#L16
* Add the workflow to branch protection to be required
