### ISSUE TITLE
Custom provisioning and deprovisioing

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#8]
**Description**

Our BTP Manager requires some custom provisioning and deprovisioning capabilities. That means we will not use default reconciliation implementation from module-manager which just creates yamls files out of chart and applies into k8s.

BTP Manager -  external and internal configuration for btp-operator component
<img src="https://user-images.githubusercontent.com/9609118/194296023-06765d55-c531-4d23-8935-58494fab147b.png" width=75% height=75%>

**Reasons**

We want to have full control over how we install btp-operator component.

**AC**
1) Provisioning requirements, activity diagram:
<img src="https://user-images.githubusercontent.com/9609118/194291979-4bcdef27-a215-4d4b-9555-b86b74adfaa8.png" width=50% height=50%>

- [x] Provisioning:
  - [x] a) use chart values customization which is right now handled by KEB ([see](https://github.com/kyma-project/control-plane/blob/6ccc673356b82b89c953cbc41e1ebecab81ba777/components/kyma-environment-broker/internal/component_input_helpers.go#L41-L72 )):  BTPOperatorPriorityClass and manager.req_cpu_limit: "10m"
  - [x] b) if secret doesn't exist then do not install btp-operator, adjust status of the BTPOperator CR
  - [x] c) only one, first BTPOperator CR could be in READY status. All other instances must be set to ERROR state with proper message. All of them must be reconciler from time to time.
  - [x] d) update documentation

2) Deprovisioning requirements, activity diagram:
<img src="https://user-images.githubusercontent.com/9609118/194299687-7c8e57e5-31a8-4a0d-8a87-2a38507ca717.png" width=50% height=50%>

- [x] Deprovisioning:
  - [x] a) When BTPOperator CR is marked to be deleted we should first delete all SBs then SIs and give max 20 minutes to have it gone. If any of those resources are not deleted inn that time, we remove finalizers on those objects (make sure that secrets created by SBs are removed too). Then when no SB, SIs anymore remove every resource created by BTPManager controller.
  - [x] b) update documentation

**Implementation ideas**
- We can still make use of module-manager implementation where helm templating is in use. That give us a possibility to not apply resource one by one, but just in one chunk.

**Comment by szwedm** [comment]
PRs related to custom provisioning:
- [replace ManifestReconciler Reconcile method with own Reconcile](https://github.com/kyma-project/btp-manager/pull/17)
- [add label for every chart resource during provisioning](https://github.com/kyma-project/btp-manager/pull/21)
- [add Secret dependency check and Reconcile on events originating from operations on the required Secret](https://github.com/kyma-project/btp-manager/pull/22)

Todo:
- manage more than one BtpOperator CR
- verify chart installation correctness, BtpOperator CR is set to Ready state even when not all chart resources are in a healthy state
- tests.

**Comment by szwedm** [comment]
The following PR introduces:
- handling many BtpOperators and limiting the operand reconciliation responsibility to the oldest BtpOperator,
- check chart resources readiness after provisioning, set Ready state only when all resources are in Ready state.
https://github.com/kyma-project/btp-manager/pull/24

Todo:
- handle Ready state,
- tests,
- docs.

**Comment by szwedm** [comment]
Handle Ready state:
https://github.com/kyma-project/btp-manager/pull/26

Provisioning tests:
https://github.com/kyma-project/btp-manager/pull/27

**Comment by szwedm** [comment]
Provisioning documentation:
https://github.com/kyma-project/btp-manager/pull/35

**Comment by szwedm** [comment]
@ukff please read my comment:
https://github.com/kyma-project/btp-manager/pull/29#issuecomment-1321212807

**Comment by szwedm** [comment]
All tasks defined in the issue are done. We can close it after #29 merges to the `dev` branch.
