### ISSUE TITLE
Check/Bug: BTP-Manager if state changes from READY to ERROR then reconciliation happen after ReadyStateRequeueInterval (15 min)

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#913]
Looks that BTP-Manager change it's own behaviour and after status change from ready to error it is not reconciled immediately, but after 15 minutes. Marcin thinks that maybe controller-runtime version bump cause that new version has changed a behaviour,  see: https://github.com/kyma-project/btp-manager/blob/89c8b69c9814a56e206068a87357cae71a3bf5ba/go.mod#L17 

Check our unit tests, try to reproduce that. If test is failing, use previous version(older controller-runtime) of the BTP manager code and run again

**Comment by MarekMichali** [comment]
There is no bug or behaviour change. If the status changes to error or warning, and the delete timestamp is zero, we don't immediately reconcile. This is our implementation from the beginning of this component.

https://github.com/kyma-project/btp-manager/blob/cb1ffe8ae132806a09fc95895bdd6c47b8622d9b/controllers/btpoperator_controller.go#L1278-L1289

**Comment by MarekMichali** [comment]
Ideas how to fix this:

-  reconcile when state changes to error. The reconcile will immediately change the status to processing and trigger a next reconcile. There is a risk that we will get into a reconcile loop
